export const SEARCH_RESULTS = 'SEARCH_RESULTS';
export const SET_FAVORITES_FROM_DATABASE = 'SET_FAVORITES_FROM_DATABASE'
export const ADD_BOOK_FAVORITES = 'ADD_BOOK_FAVORITES'
export const REMOVE_BOOK_FAVORITES = 'REMOVE_BOOK_FAVORITES'